### ISSUE TITLE
Disabling saving does not save

### ISSUE THREAD

**Issue by DamonOnYT** [Dalrae1/FiveM-Mumble-Auto-Moderation#1]
I'm attempting to set this up however when setting localAudioPath to False it has a bit of a fit and breaks

**Comment by mrleduck** [comment]
Same issue if False then it will still continue with saving and running into issue's because the path isnt set

**Comment by Dalrae1** [comment]
Thanks for bringing this to my attention!
Fixed this in commit https://github.com/Dalrae1/FiveM-Mumble-Auto-Moderation/commit/82d7e0456f3941b45a02bfa5cbdcd473cd53d4e0
