### ISSUE TITLE
Failure to launch

### ISSUE THREAD

**Issue by DeputyDutch** [Dalrae1/FiveM-Mumble-Auto-Moderation#7]
![image](https://user-images.githubusercontent.com/15605562/172121013-e35a568e-378f-4def-956e-6b470b7c45bf.png)
I'm completely python dumb. This is a fresh install of python, no other previous installs. Used 3.10.4 of python

**Comment by Dalrae1** [comment]
Should be fixed in commit 08d4b80f4c0373dbf35913d78ae014a66872de30
